Navigation Bar
khaledsaadeh/Movie-Demo pull request #3
Opened 2021-12-31 08:28 UTC by khaledsaadeh

Added the navigation bar with search functionality, search has a minor bug that will be handled in a later PR

2021-12-31 08:38 UTC, hazemturki requested changes

2021-12-31 08:38 UTC, hazemturki commented on src/components/NavBar.js
> +    "https://api.themoviedb.org/3/search/movie?api_key=4f298a53e552283bee957836a529baec&language=en-US&page=1&include_adult=false&query=";
Not sure this is the best place for such a constant.
Doesn't seem appropriate, this is a NavBar component it shouldn't define a API URL

2021-12-31 08:38 UTC, hazemturki commented on src/components/NavBar.js
> +      axios.get(API + search).then((res) => {
Please don't use simple string concatenation to add the query and instead use Axios.get options.
Please refer to the official axios docs

```suggestion
      axios.get(API, {params: search}).then((res) => {
```

2021-12-31 08:38 UTC, hazemturki commented on src/components/NavBar.js
> +  const searchHandler = (event) => {
This search handler should trigger a callBackFunction to the app, but it shouldn't be responsible for fetching data.

2021-12-31 08:38 UTC, hazemturki commented on src/App.js
> +      <NavBar passToApp={showSearchResults} />
Pass to app is an ambiguous name for a prop.
Please rename this according to the other comments in the review.

```suggestion
      <NavBar ?={showSearchResults} />
```

2021-12-31 09:36 UTC, khaledsaadeh commented
-Added API constants to the main component.
-Used the {params} option from axios.get instead of string concatenation.
-Search handler now triggers a function responsible for fetching the data, instead of fetching them itself.
-changed the passToApp prop name to a more appropiate prop name.

2022-01-04 08:17 UTC, hazemturki approved these changes

2022-01-04 08:23 UTC, merged